authors = ["Kirill Simonov <xi@resolvent.net>"]
name = "PPrint"
uuid = "58e6f5bb-1ca5-5b55-8dd3-df7fbd0a3bdf"
version = "0.1.0"

[deps]

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[targets]
test = ["Pkg"]
